### ISSUE TITLE
Error when building the site

### ISSUE THREAD

**Issue by xiaochi-liu** [sunt-programator/CodeIT#102]
## Describe the bug

Hello. I'm using the `blogdown` R package to build a website and I like this theme very much.

However, when launching the server or building the site, I encounter the error shown below.

## Expected behaviour

Build the site successfully.

## Screenshots

![image](https://user-images.githubusercontent.com/48895627/106999252-f7546700-67d9-11eb-9189-23a14760ef1a.png)

![image](https://user-images.githubusercontent.com/48895627/106999265-fde2de80-67d9-11eb-8e50-a1673e89c723.png)

## Build Environment

- OS: macOS
- Theme version/commit: where to check
- Hugo version: 0.80.0

## Preview Environment

- OS: macOS
- Browser: Chrome

**Comment by victor-pogor** [comment]
Hi @xiaochi-liu.

Can you make the first commit on the `master` branch?

**Comment by xiaochi-liu** [comment]
Thank you very much @victor-pogor. It's [here](https://github.com/xiaochi-liu/My-Blog).

I have to say this is the most beautiful and elegant theme I've seen in the Hugo theme list. Really hope it also works in `blogdown`.

**Comment by xiaochi-liu** [comment]
Hello @victor-pogor. I think it might be an error occurred with hugo? I got the following information. Hope it helps.

```
> blogdown:::serve_site()
Launching the server via the command:
  /Users/liuxiaochi/Library/Application Support/Hugo/0.80.0/hugo server --bind 127.0.0.1 -p 4321 --themesDir themes -t CodeIT -D -F --navigateToChanged
Start building sites … 
WARN 2021/02/10 17:26:30 

Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "CDN" 和 "fingerprint" 不会启用.

Built in 1154 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: posts/single.html:85:140: executing "content" at <partial "function/content.html">: error calling partial: "/Users/liuxiaochi/Documents/rstudio-project/Xiaochi-Website/CodeIT/themes/CodeIT/layouts/partials/function/content.html:4:19": execute of template failed: template: partials/function/content.html:4:19: executing "partials/function/content.html" at <partial "function/ruby.html" $content>: error calling partial: partial that returns a value needs a non-zero argument.
```




```
> blogdown::build_site()
Start building sites … 
Total in 1446 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: posts/single.html:85:140: executing "content" at <partial "function/content.html">: error calling partial: "/Users/liuxiaochi/Documents/rstudio-project/Xiaochi-Website/CodeIT/themes/CodeIT/layouts/partials/function/content.html:4:19": execute of template failed: template: partials/function/content.html:4:19: executing "partials/function/content.html" at <partial "function/ruby.html" $content>: error calling partial: partial that returns a value needs a non-zero argument.
```

**Comment by victor-pogor** [comment]
Hi @xiaochi-liu. Can you see please issue #68?

The fix will be in the next release.

**Comment by xiaochi-liu** [comment]
Get it. Thank you very much @victor-pogor
