### ISSUE TITLE
[FEATURE] Support Nested Headers beyond h2

### ISSUE THREAD

**Issue by sheldonhull** [sunt-programator/CodeIT#107]
## Describe the feature you want

Right now h1-h2 is rendered with a `#` while h3 and beyond show a pipe. This is a bit jarring. Would like to have the header show up with #, ##, ### up to h5.

## Useful reference

One cool example of how this is rendered can be seen on this page: https://www.swyx.io/temporal-transparency-update-9-auth-is-coming-2nok/
I think the style for showing header with hash makes perfect since in the styling for this UI

**Comment by sheldonhull** [comment]
I found out where to add this. 

`themes/codeit/assets/css/_page/_single.scss`

```scss
> h2 > .header-mark::before {
      content: "#";
    }
    > h3 > .header-mark::before {
      content: "##";
    }
    > h4 > .header-mark::before {
      content: "###";
    }
    > h5 > .header-mark::before {
      content: "####";
    }
```

Learned a bit on scss from this. :tada:

![Screenshot 2021-02-08 232447](https://user-images.githubusercontent.com/3526320/107319661-de131b00-6a64-11eb-8fad-c93321432ef7.png)

If you like the idea, I could submit a PR with the change.

**Comment by victor-pogor** [comment]
Hi. Thank you for contributing to this repository.

I like the idea with the `#` prefix on the headers, but I'm not sure if we need this glow effect 🙂

**Comment by sheldonhull** [comment]
@victor-pogor ha! That's my own site customization, not suggesting that as a standard 😆.
I'll submit a PR with the change then.
