### ISSUE TITLE
[FEATURE] Mapbox/CodeIT GeoJson support

### ISSUE THREAD

**Issue by trmendes** [sunt-programator/CodeIT#114]
## Describe the feature you want

- Mapbox GeoJson
  I was checking CodeIT documentation and I could not find a way to give mapbox a geojson file to load. I would like to have a few points on my map.

**Comment by victor-pogor** [comment]
Hi @trmendes. From what I understood, the theme doesn't support this feature yet. Improvements are needed.

**Comment by victor-pogor** [comment]
Hi @trmendes,

I added the GeoJson support. I added the sample config file that will be used for loading the sources and configuring the layers. These two properties are taken from the official docs of `Mapbox`.

```json
{
  "sources": [
    {
      "id": "logo",
      "properties": {
        "type": "geojson",
        "data": "/features.geojson"
      }
    }
  ],
  "layers": [
    {
      "id": "logo-layer",
      "type": "fill",
      "source": "logo",
      "paint": {
        "fill-color": ["coalesce", ["get", "fill"], "#005c7c"],
        "fill-opacity": 0.5
      }
    }
  ]
}

```

The sample shortcode with provided properties file:

```go
{{< mapbox lng=28.836 lat=47.021 zoom=8 marked=false properties="/static/features-layers.json" >}}
```

The result:

![image](https://user-images.githubusercontent.com/24962085/124505114-78d41380-ddd1-11eb-890d-e0e320a331e2.png)

**Comment by trmendes** [comment]
Super. Thanks @victor-pogor 

I look forward to trying it out with my collection :)
