### ISSUE TITLE
[FEATURE] Make TOC optional

### ISSUE THREAD

**Issue by trmendes** [sunt-programator/CodeIT#126]
-  Make TOC optional
  It would be nice to be able to enable/disable TOC for every single page (and not only to posts) as part of the header

```
---
title: 'Travel'
draft: false
toc: true or false
---
```

**Comment by victor-pogor** [comment]
Hello @trmendes!

Did you try something like this?
https://github.com/sunt-programator/CodeIT/blob/52d07a1d8f81613d70ce0a6ed1a475aed08224a4/exampleSite/config.toml#L709-L715

**Comment by victor-pogor** [comment]
Hi @trmendes.

Thank you for contributing to this repository. I like the idea. 😉
I see that documentation remains the same, no need to update.

**Comment by victor-pogor** [comment]
@all-contributors please add @trmendes for code
