### ISSUE TITLE
[BUG] Remove the Discord channel from the issue template

### ISSUE THREAD

**Issue by ktw717** [sunt-programator/CodeIT#231]
## Describe the bug
In the following message it says:
```
Briefly describe the issue you are experiencing, what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to the official [Discord channel](https://discord.com/channels/777188233284681768/777188575485493259)!
```
## Expected behavior

I click [Discord channel](https://discord.com/channels/777188233284681768/777188575485493259)! and it takes me to discord but its not seeing the server.

## UPDATE
Now, the questions can be addressed using the [Discussions](https://github.com/sunt-programator/CodeIT/discussions) tab on this repository.

**Comment by victor-pogor** [comment]
Hi @ktw717,

Now, you can ask the questions on the [Discussions](https://github.com/sunt-programator/CodeIT/discussions) tab. I created this channel when the mentioned feature wasn't present.

I'll rename this issue.

**Comment by ktw717** [comment]
No worries I thought that was the case but I wanted to check!

Thanks for taking up this project

https://github.com/sunt-programator/CodeIT/pull/234
