### ISSUE TITLE
[FEATURE] 增加 waline 评论系统

### ISSUE THREAD

**Issue by OnlyFor** [sunt-programator/CodeIT#237]
虽然valine很好，但感觉waline更好，希望作者能支持一下，

本人js水平有限，尝试按https://lewky.cn/posts/hugo-3.1.html/#%E4%BD%BF%E7%94%A8waline%E6%9B%BF%E4%BB%A3valine%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F这个教程进行配置并不成功。。。。

**Comment by victor-pogor** [comment]
Hi @OnlyFor,

Thank you for your contribution to this repository. Unfortunately, I don't speak Chinese but using the translator I understood that it would be nice to have the `waline` comment system.

I'll add this when I'll have the time. Thanks again 🙂.

**Comment by OnlyFor** [comment]
Thanks in advance !

**Comment by OnlyFor** [comment]
[pull](https://github.com/sunt-programator/CodeIT/pull/239#issue-689513449)
