### ISSUE TITLE
[FEATURE] Add "Threema" to the list of social media on homepage

### ISSUE THREAD

**Issue by KHannibal** [sunt-programator/CodeIT#285]
## Describe the feature you want

Add the messaging service [Threema](https://threema.ch/en) to the homepage.

URLs are : https://threema.id/XXXXXXXX where the X are your ID made of 8 random letters and numbers.

What is missing however is an icon...

Threema's Git is here : https://github.com/threema-ch

Thank you !

**Comment by victor-pogor** [comment]
Hi @KHannibal. Thank you for your contribution. I will add this when I have some time. 😉

PS: I found some logos [here](https://threema.ch/en/press).

**Comment by KHannibal** [comment]
> > Hi @KHannibal. Thank you for your contribution. I will add this when I'll have some time. wink
> 
> > 
> 
> > PS: I found some logos [here](https://threema.ch/en/press).
> 
> 
> 
> You don't need to find the logo, **LoveIt** originally supports [SimpleIcons](https://simpleicons.org). Look for the threema icon to find if it's available then add these lines in `themes/CodeIt/assets/data/social.yml`:
> 
> ```
> 
> # 062: Threema
> 
> threema:
> 
>   Weight: 62 
> 
>   Prefix: https://threema.id/
> 
>   Title: Threema
> 
>   Icon:
> 
>     Simpleicons: threema
> 
> ```
> 
> 
> 
> Finally, add to the `config.toml`
> 
> `Threema = "your-id"`
> 
> 
> 
> For example, this is how Threema appears in my site using SimpleIcons: [ashpex.eu.org](https://ashpex.eu.org) . I'd make a PR if that helps.

Works like a charm, huge thanks @Ashpex ! :)

@victor-pogor could you add this to the next release, please ? Thanks in advance !

**Comment by victor-pogor** [comment]
@all-contributor please add @Ashpex for code

**Comment by victor-pogor** [comment]
@all-contributors please add @KHannibal for ideas

**Comment by victor-pogor** [comment]
@all-contributors please add @Ashpex for code

**Comment by victor-pogor** [comment]
Hello @KHannibal and @Ashpex,

Thank you for your feedback and code. This will be added to the next release.
