### ISSUE TITLE
[FEATURE] Update theme demo image

### ISSUE THREAD

**Issue by victor-pogor** [sunt-programator/CodeIT#29]
### Describe the feature you want

- Update representative theme image, showing the look on different devices.

**Comment by sosiristseng** [comment]
I captured these images using Firefox's responsive design mode. Not sure if they help.

## iPhone

320 x 568

![320 x 568](https://user-images.githubusercontent.com/40054455/104341222-813f4600-5534-11eb-9d21-464b939d6e7a.png)

## iPad

1112 x 834

![1112 x 834](https://user-images.githubusercontent.com/40054455/104341279-8f8d6200-5534-11eb-9838-dee60a227a90.png)


## Fullscreen

1920 x 1080

![1920 x 1080](https://user-images.githubusercontent.com/40054455/104341305-9916ca00-5534-11eb-9d7d-56dc8e23a34d.png)

**Comment by victor-pogor** [comment]
Thanks, @sosiristseng.

I'll change the theme demo image. 👍

**Comment by sosiristseng** [comment]
I found today we can preview the mockup in [create mockup](https://www.createmockup.com/) like this

![image](https://user-images.githubusercontent.com/40054455/104677578-97abf400-5724-11eb-97d1-80891a243a4e.png)

**Comment by victor-pogor** [comment]
@sosiristseng I made the mockup in the GIMP application since I didn't know any site for automated creation of the mockups 😄
