### ISSUE TITLE
Question for improving Italian translation

### ISSUE THREAD

**Issue by xMicky24GIT** [sunt-programator/CodeIT#354]
Hi, I would like to improve the Italian translation (I'm Italian) but I have a  question:

- For the admonitions you want the text to be singular or plural? (Right now in italian it's a mix)

**Comment by victor-pogor** [comment]
Hi @xMicky24GIT,

I looked at other translations and they seem to have the singular form of text.

**Comment by xMicky24GIT** [comment]
Ok i have done the PR.
I removed the article from `allSome` because it sounded  weird in Italian since it wasn't the right one for all the words (because of male and female genre)
