### ISSUE TITLE
[FEATURE] Add a word about LoveIt to docs

### ISSUE THREAD

**Issue by nirgn975** [sunt-programator/CodeIT#46]
## Describe the feature you want

- Stale Section
  I think we need to add a word / sentence / paragraph in the README about LoveIt and to say that this repo is a successor because LoveIt become Stale (or something like that).
- Call for maintainers
  I think you need to create a new issue on LoveIt that call for maintainers to help with this repo. This will also refer people from there to here.

**Comment by victor-pogor** [comment]
Added the issue to call maintainers to contribute to this repository (dillonzq/LoveIt#565).
