### ISSUE TITLE
Unable to build website

### ISSUE THREAD

**Issue by Programazing** [sunt-programator/CodeIT#68]
## Describe the bug

I'm unable to build the site. The error is listed under Additional Information.

## Expected behavior

I expected the site to build after running `hugo server -D`

## Build Environment

- OS: Windows 10
- Theme version/commit: 0.1.0 08b7f42
- Hugo version: 0.80.0
- Hugo-extended version: 0.80.0

## Preview Environment

- OS: Windows 10
- Browser: Firefox

## Additional Information

Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: posts/single.html:92:124: executing "content" at <partial "function/content.html">: error calling partial: "C:\Dev\professional\that-amazing-programmer\website\programazing.github.io-source\themes\CodeIT\layouts\partials\function\content.html:4:19": execute of template failed: template: partials/function/content.html:4:19: executing "partials/function/content.html" at <partial "function/ruby.html" $content>: error calling partial: partial that returns a value needs a non-zero argument.

**Comment by Programazing** [comment]
I did discover that it works fine using `hugo serve`, it's just failing when I add the `-D` flag for draft previews.

**Comment by victor-pogor** [comment]
Hello @Programazing.

The problem was reported on the original theme (dillonzq/LoveIt#518}. I will make the required changes.

Does this error persist only to new posts without content? When I add the content to the posts it works.

Not working variant:
```
---
title: "My First Post"
date: 2021-01-02T12:33:17+02:00
draft: true
---


```

Working variant:
```
---
title: "My First Post"
date: 2021-01-02T12:33:17+02:00
draft: true
---

Test
```

**Comment by Programazing** [comment]
Seems it's just when there's an empty post. It took me a while to find the draft that caused the issue.

```
---
title: "TravisCi and .Net Core"
subtitle: ""
date: 2020-02-20T01:47:23-05:00
lastmod: 2020-02-20T01:47:23-05:00
draft: true
author: ""
authorLink: ""
description: ""

tags: [NUnit, .Net Core, CI/CD]
categories: [Testing]

hiddenFromHomePage: false
hiddenFromSearch: false

featuredImage: ''
featuredImagePreview: '
images: []
---
<!--more-->
```

**Comment by victor-pogor** [comment]
I am reopening this issue since it requires minor changes.

**Comment by Programazing** [comment]
Sorry about that

**Comment by sosiristseng** [comment]
We need to check if the content is empty [from this post](https://discourse.gohugo.io/t/error-with-partials-in-0-75-0/28184). So `layout/partials/function/content.html` would be:

```diff
{{- $content := .Content -}}

+ {{- if $content -}}

    {{- if .Ruby -}}
        {{- $content = partial "function/ruby.html" $content -}}
    {{- end -}}

    {{- if .Fraction -}}
        {{- $content = partial "function/fraction.html" $content -}}
    {{- end -}}

    {{- if .Fontawesome -}}
        {{- $content = partial "function/fontawesome.html" $content -}}
    {{- end -}}

    {{- $content = partial "function/checkbox.html" $content -}}

    {{- $content = partial "function/escape.html" $content -}}

+ {{- end -}}

{{- return $content -}}
```

I'm not a Go template expert so maybe there is a better way. But adding these two lines resolved the issue.

**Comment by victor-pogor** [comment]
@sosiristseng Thank you for your contribution. I will look at the PR today.

**Comment by victor-pogor** [comment]
@all-contributos please add @Programazing for bug

**Comment by victor-pogor** [comment]
@all-contributors please add @Programazing for bug
