### ISSUE TITLE
[FEATURE] Disable comments in frontmatter

### ISSUE THREAD

**Issue by michael0liver** [sunt-programator/CodeIT#72]
## Describe the feature you want

It would be nice if it were possible to disable the comments feature on certain pages via the front matter :)

**Comment by michael0liver** [comment]
Actually after looking at the template it seems you can add the following to the front matter:

```yaml
comment:
  enable: false
```

Can this be added to the documentation and CodeIT/archetypes/default.md?

**Comment by Programazing** [comment]
It is in the [documentation](https://codeit.suntprogramator.dev/theme-documentation-content/#front-matter)

You can also just use `comment: false` if you want to make it more compact

I agree it should be included in the default archetype but at worst you can just override it with your own

**Comment by michael0liver** [comment]
> It is in the [documentation](https://codeit.suntprogramator.dev/theme-documentation-content/#front-matter)

My bad I must of skimmed past that.

> You can also just use `comment: false` if you want to make it more compact

That is a nice shorthand thanks!!

> I agree it should be included in the default archetype but at worst you can just override it with your own

Closing as I have sorted my own issue 😄
