### ISSUE TITLE
[BUG] The demo website is not accessible from Southeast Asia

### ISSUE THREAD

**Issue by azharlihan** [sunt-programator/CodeIT#75]
Website https://codeit.suntprogramator.dev/ is not accessible from Southeast Asia. When I visit the website, it displays Error 522 (Connection Timeout). When I visit the website as another country (ex: Netherland) using VPN, the website appears normally. However, not everyone in Southeast Asia uses a VPN.

#### Screenshoot Using Google Chrome Windows 10
![Cloudflare 522](https://user-images.githubusercontent.com/46442361/104253773-e4cf6200-54a7-11eb-9ced-840754197c2f.JPG)
----
#### HTTP Check using [Check Host](https://check-host.net/check-http?host=https://codeit.suntprogramator.dev/)
![Screenshot_2021-01-12 Check website performance and response Check host - online website monitoring](https://user-images.githubusercontent.com/46442361/104253776-e862e900-54a7-11eb-878c-510c6c458b31.png)

**Comment by victor-pogor** [comment]
Hi @azharlihan.

I'm sorry about your issue. It seems to be a problem with Cloudflare.

I would like to write to its support team but as far as I understood it will be useful to provide him the trace information. Can you access please [this link](https://suntprogramator.dev/cdn-cgi/trace) and provide here the `colo` value?

If you want to read more information about this parameter, you can access the `Identify the Cloudflare data center serving your request` section at [this link](https://support.cloudflare.com/hc/en-us/articles/203118044-Gathering-information-for-troubleshooting-sites).

Thank you.

**Comment by azharlihan** [comment]
I have accessed [the link](https://suntprogramator.dev/cdn-cgi/trace) and the colo value that I get is `SIN`

below is the complete information
```
fl=35f678
h=suntprogramator.dev
ip=103.143.98.198
ts=1610694018.521
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
colo=SIN
http=http/2
loc=ID
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
```

**Comment by victor-pogor** [comment]
Ok, I will try to write to the support team.

PS: I edited your comment because it contained the IP address which I think is some kind of personal data.

**Comment by azharlihan** [comment]
Oww okay. sorry about that 😅

**Comment by victor-pogor** [comment]
Hello @azharlihan. It seems to be a problem with your ISP.

You can read about your error [here](https://support.cloudflare.com/hc/en-us/articles/115003011431-Troubleshooting-Cloudflare-5XX-errors#522error) and [here](https://community.cloudflare.com/t/502-errors-in-singapore/199117/3).

Unfortunately, I can't help you to access the blog theme, since the problem may be related to your provider, but you can build and run the theme locally, using the instruction in the `README` file. 🙂
