### ISSUE TITLE
[BUG] Search icon layout shift on window resize

### ISSUE THREAD

**Issue by michael0liver** [sunt-programator/CodeIT#76]
## Describe the bug

Upon resizing of the window the search icon shifts. I have tested it in Chrome, Firefox and Safari and I can only reproduce on Firefox.  

#### Firefox
![Jan-12-2021 09-23-41](https://user-images.githubusercontent.com/55017335/104296227-48ae5680-54b9-11eb-9336-bc8c9af094d1.gif)

#### Chrome
![Jan-12-2021 09-42-36](https://user-images.githubusercontent.com/55017335/104297246-8c559000-54ba-11eb-973c-922af1a188f8.gif)

## Build Environment

- OS: macOS
- Theme version/commit https://github.com/sunt-programator/CodeIT/commit/504db875f1ade8bda962adb8b79dbe9adc8b90d0
- Hugo version v0.80.0/extended darwin/amd64

Please try to use Hugo **extended** version before opening the issue.

## Preview Environment

- OS: macOS
- Browser Firefox 84.0.2 (64-bit)

**Comment by Programazing** [comment]
I noticed it moves when I click any of my links then snaps back into place

![search](https://user-images.githubusercontent.com/11393826/104490423-d3b54c80-559e-11eb-9a77-d401db40beb8.png)

**Comment by victor-pogor** [comment]
Hi @michael0liver and @Programazing. 

I hard-coded the `top` and `bottom` attributes 😄

https://github.com/sunt-programator/CodeIT/blob/d46221ce1148f1a9eeeef6c4d063632586d2a7e3/assets/css/_partial/_header.scss#L99-L100
