### ISSUE TITLE
[FEATURE] ORCID id to frontpage

### ISSUE THREAD

**Issue by epogrebnyak** [sunt-programator/CodeIT#82]
## Describe the feature you want

On front pade add ORCID pictogram. In config.toml would be adding to `[languages.en.params.social]` https://github.com/sunt-programator/CodeIT/blob/504db875f1ade8bda962adb8b79dbe9adc8b90d0/exampleSite/config.toml#L157

## Useful reference

Here is my example where an ID could have pointed to <https://orcid.org/0000-0003-3914-9665>

**Comment by victor-pogor** [comment]
@all-contributors please add @epogrebnyak for ideas
