### ISSUE TITLE
[Enhancement] Hoover on avatar

### ISSUE THREAD

**Issue by epogrebnyak** [sunt-programator/CodeIT#83]
Pointing mouse on avatar on front page gives the filename, but as an enhancement it could give author name.

![изображение](https://user-images.githubusercontent.com/9265326/104834756-97416380-58b2-11eb-9001-d03b14b9db14.png)

**Comment by epogrebnyak** [comment]
Sorry I lavelled this as a bug

**Comment by victor-pogor** [comment]
Hi @epogrebnyak. Thank you for your contribution. I made a PR (#84) for this issue.

**Comment by victor-pogor** [comment]
@all-contributors please add @epogrebnyak for bug

**Comment by epogrebnyak** [comment]
@victor-pogor thank you for such a prompt update! LoveIt is super functional theme (the shortcodes, the appearance, the simplicity) and I appreate you taking care of CodeIT fork. It appeals to me you give all the approrate credit to original theme author and preserve the language versions. Great work!
