### ISSUE TITLE
[FEATURE] Add Telegram as sharing option

### ISSUE THREAD

**Issue by mwolfaardt** [sunt-programator/CodeIT#93]
## Describe the feature you want
The theme have a lot of sharing options, except the new big players, signal and telegram. Add the options in the config file for blog posts to be shared using these mediums

**Comment by victor-pogor** [comment]
Hello @mwolfaardt.

Thank you for contributing to this theme.

I will add these sharing options.

**Comment by victor-pogor** [comment]
Hi @mwolfaardt.

I added the Telegram sharing option, however, I didn't add the Signal sharing option since it does not have this option (as far as I understood).
