### ISSUE TITLE
[FEATURE] Feather fonts option

### ISSUE THREAD

**Issue by epogrebnyak** [sunt-programator/CodeIT#94]
## Describe the feature you want

- The icon for Github in LoveIt/CodeIT looks like like funny pig, and not octopus, once you see it, hard to unsee. 
Maybe there is a way to change that icon or a set of icons to another font? Feather (below) looks nice!

This may be minor and subjective, and may need to go into the theme, I'd be happy if someone tells where the symbol for github is set and how to override tit.

## Useful reference

- https://feathericons.com/
- https://github.com/vaga/hugo-theme-m10c

**Comment by victor-pogor** [comment]
It was funny 🤣. The change is simple. `CodeIT` uses `Font Awesome` font. You can simply change this line from `fab fa-github-alt fa-fw` to `fab fa-github fa-fw`.

https://github.com/sunt-programator/CodeIT/blob/1d2e25027b591b667521825b50cce3b48e7c1f7a/assets/data/social.yml#L7

And the icon will be as [you want](https://fontawesome.com/icons/github?style=brands) 🙂.
